version: '3'

services:
  frontend:
    build:
      context: ../front-end
    ports:
      - "3000:80"
    networks:
      - mynetwork

  backend:
    build:
      context: ../backend
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
